name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - master

jobs:
  build_and_deploy_job:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    permissions:
        id-token: write
        contents: read
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true

      # New Step 1: Setup Node.js environment
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18 # Specify your desired Node.js version

      # New Step 2: Install Terser and run minification
      - name: Build and Minify JavaScript
        run: |
          # Install Terser, a modern JavaScript minifier
          npm install terser -g
          
          # Create an output directory for the optimized files
          # Note: We are also copying non-JS files like HTML, CSS, images, etc.
          # The `rsync` command is great for this.
          rsync -a --exclude='*.js' ./ build/
          
          # Find all .js files, minify them, and place them in the build directory
          # preserving the folder structure.
          for file in $(find . -name "*.js"); do
            echo "Minifying $file..."
            # Create the target directory inside 'build' if it doesn't exist
            mkdir -p "$(dirname "build/$file")"
            # Run terser
            terser "$file" -o "build/$file" -c -m
          done
      - name: Build And Deploy
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_MANGO_GROUND_0A971A10F }}
          action: "upload"
          ###### Repository/Build Configurations - These values can be configured to match your app requirements. ######
          # For more information regarding Static Web App workflow configurations, please visit: https://aka.ms/swaworkflowconfig
          app_location: "/" # App source code path
          api_location: "" # Api source code path - optional
          output_location: "build" # Built app content directory - optional
          github_id_token: ${{ steps.idtoken.outputs.result }}
          skip_app_build: true
          ###### End of Repository/Build Configurations ######

  close_pull_request_job:
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    runs-on: ubuntu-latest
    name: Close Pull Request Job
    steps:
      - name: Close Pull Request
        id: closepullrequest
        uses: Azure/static-web-apps-deploy@v1
        with:
          action: "close"
